# Sphinx config for the generated class reference (see .github/workflows/ci.yml
# docs job — docs/classes/ is generated by godot --doctool + make_rst.py).
project = "DroneSim"
author = "Tim Bittner"
copyright = "2026, Tim Bittner"
exclude_patterns = ["_build", "publishing.md"]
html_theme = "furo"
html_title = "DroneSim"
# make_rst output references engine classes that have no page here; silence
# the cross-reference warnings instead of shipping 400 engine pages.
suppress_warnings = ["ref.ref"]
