@tool
class_name DroneBodyMesh
extends MeshInstance3D

## Builds a rhombic (diamond) prism — 8 vertices, 12 triangles.
## Reminiscent of the Nier Automata hacking-minigame drone silhouette.
##
## The widest point of the diamond is pushed ~4/5 of the way from front
## to back, giving it a longer, more gradual taper forward (-Z) and a short
## blunt rear (+Z). Height is uniform.
##
## Normals are auto-generated by Godot.

func _ready() -> void:
	mesh = _build_mesh()

func _build_mesh() -> ArrayMesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)

	var h := 0.05     # half-height

	# Diamond shape: front tip at -Z (forward), back at +Z (rear).
	# Side vertices sit at Z = 0.096, roughly 4/5 from front to back.
	var front_z := -0.16   # front tip at -Z (forward)
	var side_z  := 0.096   # widest point behind center, toward +Z
	var back_z  := 0.16    # rear at +Z
	var half_w  := 0.12

	# Top face (y = +h)
	var ft := Vector3(0.0,      h,  front_z)
	var rt := Vector3( half_w,  h,  side_z)
	var bt := Vector3(0.0,      h,  back_z)
	var lt := Vector3(-half_w,  h,  side_z)

	# Bottom face (y = -h)
	var fb := Vector3(0.0,     -h,  front_z)
	var rb := Vector3( half_w, -h,  side_z)
	var bb := Vector3(0.0,     -h,  back_z)
	var lb := Vector3(-half_w, -h,  side_z)

	# Top face (looking down +Y) — CCW: front → right → back → left
	_st_quad(st, ft, rt, bt, lt)

	# Bottom face (looking up -Y) — CCW: front → left → back → right
	_st_quad(st, fb, lb, bb, rb)

	# Sides (CCW from outside)
	_st_quad(st, fb, ft, rt, rb)  # front-right
	_st_quad(st, rb, rt, bt, bb)  # back-right
	_st_quad(st, bb, bt, lt, lb)  # back-left
	_st_quad(st, lb, lt, ft, fb)  # front-left

	st.generate_normals()
	st.index()
	return st.commit()


static func _st_quad(st: SurfaceTool, a: Vector3, b: Vector3, c: Vector3, d: Vector3) -> void:
	st.add_vertex(a)
	st.add_vertex(b)
	st.add_vertex(c)
	st.add_vertex(a)
	st.add_vertex(c)
	st.add_vertex(d)
